apiVersion: v1
kind: Service
metadata:
  name: app3-service
  namespace: default
spec:
  selector:
    app.kubernetes.io/name: hello-kubernetes-3
    app.kubernetes.io/instance: app3-deployment
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/component: app3
    app.kubernetes.io/part-of: part-2
  type: ClusterIP
  ports:
  - name: app3-service
    protocol: TCP
    port: 80
    targetPort: 8080
