apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kub1
  labels:
    app: hello-kub1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-kub1
  template:
    metadata:
      name: hello-kub1
      labels:
        app: hello-kub1
    spec:
      containers:
        - name: hello-kub1
          image: paulbouwer/hello-kubernetes:1.10.1
          ports:
            - containerPort: 8080
          env:
            - name: MESSAGE
              value: "App 1 motherfucker"

      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: hello-kub1-service
spec:
  type: NodePort
  selector:
    app: hello-kub1
  ports:
    - protocol: TCP
      ports: 80
      targetPort: 8080
      NodePort: 30080
---
