# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.define "bpoumeauS" do |server| 
    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://vagrantcloud.com/search.
    server.vm.box = "debian/bookworm64"
    server.vm.box_check_update = false

    server.vm.synced_folder "token/", "/token", create: true
  
    # server du hostname et du network
    # https://developer.hashicorp.com/vagrant/docs/networking/basic_usage
    server.vm.hostname = "bpoumeauS"
    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    server.vm.network "private_network", ip: "192.168.56.110"
  
    server.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      # vb.gui = true
      # Customize the amount of memory on the VM:
      vb.cpus = "3"
      vb.memory = "2048"
    end
    # Enable provisioning with a shell script. Additional provisioners such as
    # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
    # documentation for more information about their specific syntax and use.
    server.vm.provision "shell", path: "server.sh"
  end

  config.vm.define "bpoumeauSW" do |worker| 
    worker.vm.box = "debian/bookworm64"
    worker.vm.box_check_update = false
    worker.vm.hostname = "bpoumeauSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.synced_folder "token/", "/token", disabled: false
  
    worker.vm.provider "virtualbox" do |vb|
      vb.cpus = "3"
      vb.memory = "2048"
    end
    worker.vm.provision "shell", path: "worker.sh"
  end
end
