apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
  namespace: default
  labels:
    app.kubernetes.io/name: hello-kubernetes-2
    app.kubernetes.io/instance: app2-deployment
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/component: app2
    app.kubernetes.io/part-of: part-2
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-kubernetes-2
      app.kubernetes.io/instance: app2-deployment
      app.kubernetes.io/version: "0.0.1"
      app.kubernetes.io/component: app2
      app.kubernetes.io/part-of: part-2
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-kubernetes-2
        app.kubernetes.io/instance: app2-deployment
        app.kubernetes.io/version: "0.0.1"
        app.kubernetes.io/component: app2
        app.kubernetes.io/part-of: part-2
    spec:
      containers:
      - name: app2-deployment
        image: paulbouwer/hello-kubernetes:1.10.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        env:
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: app2-config
                key: message
        ports:
        - containerPort: 8080
          name: app2-port
      restartPolicy: Always
